# Generated by Django 5.0.4 on 2024-07-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_author_email_post_main_post_date_fa4454_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(blank=True, default='default@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
